version: "3"

services:
  fastapi:
    container_name: fastapi
    build:
        context: ./app/
        dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always
  web:
    container_name: web
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - './ui:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
